name: Go

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - run: go get github.com/yuin/goldmark
    
    - run: github.com/yuin/goldmark-highlighting
    
    - name: Build
      run: go build -o cider *.go
    
    - name: generate
      run: ./cider
      
      
